global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: unordered-producer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - unordered-producer-api:8080

  - job_name: unordered-workers
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - unordered-worker-1:8080
          - unordered-worker-2:8080

  - job_name: sharded-producer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - sharded-producer-api:8080

  - job_name: shard-workers
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - shard-worker-0:8080
          - shard-worker-1:8080
          - shard-worker-2:8080
          - shard-worker-3:8080
